/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ConnectionsIndexRouteImport } from './routes/connections.index'
import { Route as ConnectionsConnectionIdRouteImport } from './routes/connections.$connectionId'
import { Route as SSessionIdRouteImport } from './routes/s.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsIndexRoute = ConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsConnectionIdRoute = ConnectionsConnectionIdRouteImport.update({
  id: '/connections/$connectionId',
  path: '/connections/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SSessionIdRoute = SSessionIdRouteImport.update({
  id: '/s/$sessionId',
  path: '/s/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/saved': typeof SavedRoute
  '/connections/$connectionId': typeof ConnectionsConnectionIdRoute
  '/s/$sessionId': typeof SSessionIdRoute
  '/connections/': typeof ConnectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/saved': typeof SavedRoute
  '/connections/$connectionId': typeof ConnectionsConnectionIdRoute
  '/s/$sessionId': typeof SSessionIdRoute
  '/connections': typeof ConnectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/saved': typeof SavedRoute
  '/connections/$connectionId': typeof ConnectionsConnectionIdRoute
  '/s/$sessionId': typeof SSessionIdRoute
  '/connections/': typeof ConnectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/saved'
    | '/connections/$connectionId'
    | '/s/$sessionId'
    | '/connections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/saved'
    | '/connections/$connectionId'
    | '/s/$sessionId'
    | '/connections'
  id:
    | '__root__'
    | '/'
    | '/saved'
    | '/connections/$connectionId'
    | '/s/$sessionId'
    | '/connections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SavedRoute: typeof SavedRoute
  ConnectionsConnectionIdRoute: typeof ConnectionsConnectionIdRoute
  SSessionIdRoute: typeof SSessionIdRoute
  ConnectionsIndexRoute: typeof ConnectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/': {
      id: '/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof ConnectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/$connectionId': {
      id: '/connections/$connectionId'
      path: '/connections/$connectionId'
      fullPath: '/connections/$connectionId'
      preLoaderRoute: typeof ConnectionsConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$sessionId': {
      id: '/s/$sessionId'
      path: '/s/$sessionId'
      fullPath: '/s/$sessionId'
      preLoaderRoute: typeof SSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SavedRoute: SavedRoute,
  ConnectionsConnectionIdRoute: ConnectionsConnectionIdRoute,
  SSessionIdRoute: SSessionIdRoute,
  ConnectionsIndexRoute: ConnectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
